create index if not exists activity_log_actor_user_idx on public.activity_log(actor_user_id);
create index if not exists check_ins_user_id_idx on public.check_ins(user_id);
create index if not exists decisions_area_id_idx on public.decisions(area_id);
create index if not exists decisions_area_workspace_idx on public.decisions(area_id, workspace_id);
create index if not exists decisions_project_id_idx on public.decisions(project_id);
create index if not exists decisions_project_workspace_idx on public.decisions(project_id, workspace_id);
create index if not exists decisions_user_id_idx on public.decisions(user_id);
create index if not exists events_user_id_idx on public.events(user_id);
create index if not exists goals_area_id_idx on public.goals(area_id);
create index if not exists goals_area_workspace_idx on public.goals(area_id, workspace_id);
create index if not exists ideas_area_id_idx on public.ideas(area_id);
create index if not exists ideas_area_workspace_idx on public.ideas(area_id, workspace_id);
create index if not exists ideas_project_id_idx on public.ideas(project_id);
create index if not exists ideas_project_workspace_idx on public.ideas(project_id, workspace_id);
create index if not exists ideas_user_id_idx on public.ideas(user_id);
create index if not exists projects_area_id_idx on public.projects(area_id);
create index if not exists projects_area_workspace_idx on public.projects(area_id, workspace_id);
create index if not exists projects_goal_id_idx on public.projects(goal_id);
create index if not exists projects_goal_workspace_idx on public.projects(goal_id, workspace_id);
create index if not exists route_steps_created_by_idx on public.route_steps(created_by);
create index if not exists route_steps_route_workspace_idx on public.route_steps(route_id, workspace_id);
create index if not exists route_steps_workspace_idx on public.route_steps(workspace_id);
create index if not exists routes_created_by_idx on public.routes(created_by);
create index if not exists routes_goal_workspace_idx on public.routes(goal_id, workspace_id);
create index if not exists routines_area_id_idx on public.routines(area_id);
create index if not exists routines_area_workspace_idx on public.routines(area_id, workspace_id);
create index if not exists routines_user_id_idx on public.routines(user_id);
create index if not exists tasks_area_id_idx on public.tasks(area_id);
create index if not exists tasks_area_workspace_idx on public.tasks(area_id, workspace_id);
create index if not exists tasks_project_id_idx on public.tasks(project_id);
create index if not exists tasks_project_workspace_idx on public.tasks(project_id, workspace_id);
create index if not exists tasks_route_step_workspace_idx on public.tasks(route_step_id, workspace_id);